-- Adicionar colunas à tabela sales (se não existirem)
ALTER TABLE public.sales
  ADD COLUMN IF NOT EXISTS client_name TEXT,
  ADD COLUMN IF NOT EXISTS client_cpf_encrypted TEXT,
  ADD COLUMN IF NOT EXISTS client_contact TEXT,
  ADD COLUMN IF NOT EXISTS passengers INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS trip_type TEXT,
  ADD COLUMN IF NOT EXISTS channel TEXT NOT NULL DEFAULT 'internal',
  ADD COLUMN IF NOT EXISTS sale_source TEXT,
  ADD COLUMN IF NOT EXISTS program_id UUID,
  ADD COLUMN IF NOT EXISTS mileage_account_id UUID,
  ADD COLUMN IF NOT EXISTS payment_method TEXT,
  ADD COLUMN IF NOT EXISTS payment_status TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS created_by UUID,
  ADD COLUMN IF NOT EXISTS user_id UUID,
  ADD COLUMN IF NOT EXISTS miles_used NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_cost NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cost_per_thousand NUMERIC(18,2),
  ADD COLUMN IF NOT EXISTS sale_price NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS profit NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS profit_margin NUMERIC(6,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS price_total NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS margin_value NUMERIC(18,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS margin_percentage NUMERIC(6,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS price_per_passenger NUMERIC(18,2),
  ADD COLUMN IF NOT EXISTS boarding_fee NUMERIC(18,2),
  ADD COLUMN IF NOT EXISTS airline_program TEXT,
  ADD COLUMN IF NOT EXISTS locator_code TEXT,
  ADD COLUMN IF NOT EXISTS passenger_cpfs JSONB,
  ADD COLUMN IF NOT EXISTS flight_segments JSONB,
  ADD COLUMN IF NOT EXISTS route_text TEXT,
  ADD COLUMN IF NOT EXISTS seller_name TEXT,
  ADD COLUMN IF NOT EXISTS seller_contact TEXT,
  ADD COLUMN IF NOT EXISTS counter_cost_per_thousand NUMERIC(18,2),
  ADD COLUMN IF NOT EXISTS counter_seller_name TEXT,
  ADD COLUMN IF NOT EXISTS counter_seller_contact TEXT,
  ADD COLUMN IF NOT EXISTS counter_airline_program TEXT;

-- Criar tabela sale_segments (se não existir)
CREATE TABLE IF NOT EXISTS public.sale_segments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sale_id UUID NOT NULL REFERENCES public.sales(id) ON DELETE CASCADE,
  direction TEXT NOT NULL CHECK (direction IN ('oneway','roundtrip','multicity')),
  from_code TEXT NOT NULL,
  to_code TEXT NOT NULL,
  date TIMESTAMPTZ,
  flight_number TEXT,
  position INT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);